Add empty export to allow compiling
src/modules/template/components/index.ts(1,1): error TS1208: 'index.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.